[build]
  publish = "public"
  functions = "functions"
  command = "npm install" # 👈 Elimina "npm run build" si no lo necesitas

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
